apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-devcontainer
  labels:
    app: products-devcontainer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: products-devcontainer
  template:
    metadata:
      labels:
        app: products-devcontainer
    spec:
      restartPolicy: Always
      containers:
      - name: products-devcontainer
        image: products-devcontainer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: redis-creds
                key: database-uri
        resources:
          limits:
            cpu: "0.25"
            memory: "64Mi"
          requests:
            cpu: "0.10"
            memory: "32Mi"