apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REPO
      description: URL to git repo
      type: string
    - name: GIT_REF
      description: Reference to branch
      type: string
      default: "fix-db-bug-openshift" # This default is correct
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision # Note: The git-clone task uses 'revision', not 'REVISION'
          value: $(params.GIT_REF)
    - name: pylint
      taskRef:
        name: pylint
        kind: Task
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: path
          value: service
    # --- THIS IS THE FIX ---
    # The pytest task does not need any params. They have been removed.
    - name: pytest
      taskRef:
        name: pytest
        kind: Task
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace