apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
  namespace: aa1020-dev
spec:
  params:
    - name: GIT_REPO
      description: URL to git repo
      type: string
    - name: GIT_REF
      description: Reference to branch
      type: string
      default: master
  
  # This section was missing
  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)

    - name: pylint
      taskRef:
        name: pylint
        kind: Task
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: path
          value: service

    - name: pytest
      taskRef:
        name: pytest
        kind: Task
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: secret-name
          value: "postgres-creds"
        - name: secret-key
          value: "database_uri"