apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pylint
spec:
  description: This task will run pylint on the provided input using pipenv.
  params:
    - default: "service"
      description: The path to the module which should be analysed by pylint
      name: path
      type: string
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install pipenv
        pipenv install --dev
        pipenv run pylint $(params.path)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest
spec:
  workspaces:
    - name: source
  steps:
    - name: pytest
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -ex
        pip install pipenv
        pipenv install --dev
        pipenv run pytest tests/
      env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: postgres_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_db