apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
      volume.kubernetes.io/selected-node: ip-10-0-30-242.ec2.internal
      volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    creationTimestamp: "2025-08-03T00:19:29Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: pipeline-pvc
    namespace: mp6828-dev
    resourceVersion: "3108678642"
    uid: edc275b9-0c50-46c2-8ed3-3bd6a7908c3f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: gp3
    volumeMode: Filesystem
    volumeName: pvc-edc275b9-0c50-46c2-8ed3-3bd6a7908c3f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
